//! orin-bench — benchmark suite for orin.
//!
//! This binary generates synthetic filesystem trees and measures
//! index build time, query latency, memory usage, and snapshot performance.

use clap::{Parser, Subcommand};
use std::path::PathBuf;

mod corpus;
mod queries;
mod runner;
mod stats;
mod report;

#[derive(Parser, Debug)]
#[command(name = "orin-bench", version, about = "orin benchmark suite")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Generate a synthetic filesystem corpus
    Gen {
        /// Corpus size: tiny, medium, large, real-home
        #[arg(short, long, default_value = "medium")]
        corpus: String,
        /// Output directory
        #[arg(short, long)]
        out: PathBuf,
        /// Random seed (hex)
        #[arg(long, default_value = "0xC0FFEE")]
        seed: String,
    },
    /// Run benchmarks against a corpus
    Run {
        /// Tool to benchmark: orin, fd, find, rg
        #[arg(short, long)]
        tool: String,
        /// Corpus directory (generated by gen)
        #[arg(short, long)]
        corpus: PathBuf,
        /// Query matrix file
        #[arg(short, long, default_value = "queries.json")]
        queries: PathBuf,
        /// Iterations per query
        #[arg(short, long, default_value = "1000")]
        iterations: usize,
        /// Output results JSON
        #[arg(short, long)]
        out: PathBuf,
    },
    /// Compare benchmark results and generate markdown report
    Compare {
        /// Results directory (artifacts from bench runs)
        #[arg(short, long)]
        results: PathBuf,
        /// Output markdown report
        #[arg(short, long, default_value = "comparison.md")]
        out: PathBuf,
    },
}

fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Gen { corpus, out, seed } => {
            let seed = u64::from_str_radix(seed.strip_prefix("0x").unwrap_or(&seed), 16)?;
            corpus::generate(&corpus, &out, seed)?;
        }
        Commands::Run { tool, corpus, queries, iterations, out } => {
            runner::run(&tool, &corpus, &queries, iterations, &out)?;
        }
        Commands::Compare { results, out } => {
            report::compare(&results, &out)?;
        }
    }

    Ok(())
}


