[package]
name = "orin-daemon"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
orin-core = { path = "../orin-core" }
anyhow = { workspace = true }
interprocess = { workspace = true }
notify = { workspace = true }
ignore = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ctrlc = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }
bytemuck = { workspace = true }
crc32fast = { workspace = true }
sysinfo = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[features]
default = []